### ISSUE TITLE
Advanced Seared Drain crash: `ClassCastException: TileTinkerTank cannot be cast to TileSmeltery`

### ISSUE THREAD

**Issue by Krutoy242** [tgstyle/MCT-Smeltery-IO#6]
Forming **Seared Tank** multiblock with `Advanced Seared Drain` instead of default `Seared Drain` causing crash:

```ruby
java.lang.ClassCastException: slimeknights.tconstruct.smeltery.tileentity.TileTinkerTank cannot be cast to slimeknights.tconstruct.smeltery.tileentity.TileSmeltery
    at mctmods.smelteryio.tileentity.base.TileEntityBase.getMasterTile(TileEntityBase.java:220)
    at mctmods.smelteryio.tileentity.TileEntityAD.getSmeltery(TileEntityAD.java:71)
    at mctmods.smelteryio.tileentity.TileEntityAD.TickCentral_TrueITickableUpdate(TileEntityAD.java:53)
    at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48)
    at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:94)
    at mctmods.smelteryio.tileentity.TileEntityAD.update(TileEntityAD.java)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:1838)
```

Discovered in [E2EE modpack](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/397).

## Log: https://mclo.gs/ms8JtiV

**Comment by tgstyle** [comment]
Release 1.3 fixed all prior issues. It is not back compatible with 1.2.
